apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-rust-template
  title: Simple Rust Template
  description: Creates a GitHub repository from a Rust service template.
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository Information
      required:
        - name
        - repoUrl
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the new repository.
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-template
      name: Fetch Go Template
      action: fetch:template
      input:
        url: https://github.com/pedrojbDev/rust-template-backstage/tree/main/rust-base
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "Generated Go service for ${{ parameters.name }}"
        repoUrl: ${{ parameters.repoUrl }}

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}